export const SAMPLE_STORIES = [
  { title: 'The Little Cat', text: 'The cat sat on the mat. It was a big fat cat. The cat had a red hat. The cat was very happy.' },
  { title: 'A Fun Day', text: 'Sam went to the park. He saw a big dog. The dog ran fast. Sam and the dog played all day. It was a fun day.' },
  { title: 'The Red Ball', text: 'Tom had a red ball. He kicked the ball far. The ball went over the wall. Tom ran to get it back. He found the ball in the garden.' },
  { title: 'My Pet Fish', text: 'I have a pet fish. It is blue and red. It swims in a big tank. I feed it every day. My fish is my best friend.' },
  { title: 'The Big Tree', text: 'There is a big tree in our yard. It has green leaves. Birds sit on the tree. I like to sit under the tree. It gives us shade.' },
  { title: 'A Rainy Day', text: 'It rained all day. I wore my yellow boots. I jumped in the puddles. Splash splash splash. I love rainy days.' },
  { title: 'The Ice Cream', text: 'Mom got me ice cream. It was pink and cold. I licked it fast. It dripped on my hand. It was so yummy.' },
  { title: 'My New Shoes', text: 'I got new shoes today. They are red and white. I can run so fast in them. I wore them to school. All my friends liked them.' },
  { title: 'The Puppy', text: 'We got a new puppy. He is small and brown. He likes to jump and play. He licks my face. I named him Max.' },
  { title: 'At the Beach', text: 'We went to the beach. The sand was hot. I made a sand castle. The waves came and washed it away. I built it again.' },
  { title: 'The Sun', text: 'The sun is big and bright. It comes up in the morning. It goes down at night. The sun keeps us warm. I love sunny days.' },
  { title: 'My Bike', text: 'I have a blue bike. I ride it every day. I go fast down the hill. I ring the bell. Ding ding ding.' },
  { title: 'The Bunny', text: 'I saw a bunny in the garden. It was white and fluffy. It had long ears. It hopped around. Then it ran away.' },
  { title: 'Bedtime', text: 'It is time for bed. I brush my teeth. Mom reads me a story. I hug my teddy bear. Good night, sleep tight.' },
  { title: 'The Farm', text: 'We went to a farm. I saw cows and pigs. The chickens said cluck cluck. The rooster said cock-a-doodle-doo. I fed the goats.' },
  { title: 'My Lunch Box', text: 'I packed my lunch box. I put in a sandwich. I added an apple. I put in some crackers. I am ready for school.' },
  { title: 'The Frog', text: 'I found a frog by the pond. It was green and slimy. It jumped into the water. Ribbit ribbit. The frog swam away.' },
  { title: 'Snow Day', text: 'It snowed last night. The ground is all white. I made a snowman. He has a carrot nose. I gave him a scarf.' },
  { title: 'The Rainbow', text: 'After the rain I saw a rainbow. It had many colors. Red orange yellow green blue. It was so pretty. I wished I could touch it.' },
  { title: 'My Garden', text: 'I planted seeds in the garden. I gave them water. The sun helped them grow. Now I have flowers. They are red and yellow.' },
  { title: 'The Duck', text: 'I saw a duck at the lake. It was swimming in the water. It had yellow babies. They followed their mom. Quack quack quack.' },
  { title: 'The Cookie', text: 'Mom baked cookies today. They smelled so good. I had one with milk. It was warm and sweet. Can I have one more please.' },
  { title: 'My Hat', text: 'I have a funny hat. It is big and purple. I wear it when I play. My friends laugh at my hat. I think it is cool.' },
  { title: 'The Moon', text: 'The moon is out tonight. It is big and round. It shines so bright. The stars twinkle next to it. I see the moon from my window.' },
  { title: 'The Ant', text: 'I saw an ant on the ground. It was very small. It carried a big crumb. It walked in a line. Ants work very hard.' },
  { title: 'My Toy Box', text: 'I have a big toy box. It has cars and blocks. It has dolls and bears. I play with my toys every day. Then I put them back.' },
  { title: 'The Bus', text: 'I ride the bus to school. It is big and yellow. The driver says hello. I sit with my friend. The bus goes beep beep.' },
  { title: 'The Kite', text: 'I flew a kite today. It went up high in the sky. The wind made it dance. It was red and blue. I held on tight.' },
  { title: 'The Apple', text: 'I picked an apple from the tree. It was big and red. I took a bite. It was sweet and juicy. Apples are my favorite fruit.' },
  { title: 'Bathtime', text: 'It is time for a bath. I fill the tub with water. I add bubbles. I play with my rubber duck. Splish splash I am clean.' },
  { title: 'The Butterfly', text: 'I saw a butterfly in the garden. It had orange wings. It flew from flower to flower. It landed on my hand. Then it flew away.' },
  { title: 'The Train', text: 'I like trains. They go on tracks. Choo choo choo. The train is long and fast. I wave at the train as it goes by.' },
  { title: 'My Friend', text: 'My best friend is Lily. We play at the park. We swing on the swings. We slide down the slide. We have so much fun.' },
  { title: 'The Teddy Bear', text: 'I have a teddy bear. His name is Ben. He is soft and brown. I take him to bed every night. He keeps me safe.' },
  { title: 'The Stars', text: 'I look up at the sky at night. I see so many stars. They twinkle and shine. I try to count them. One two three four five.' },
  { title: 'The Pancake', text: 'Dad made pancakes for breakfast. He flipped them in the pan. I put syrup on top. I ate three pancakes. They were so good.' },
  { title: 'The Bird', text: 'A bird sat on my window. It was small and blue. It sang a pretty song. Tweet tweet tweet. Then it flew to the tree.' },
  { title: 'The Balloon', text: 'I got a red balloon. I held the string tight. The wind tried to take it. I let it go up up up. It went into the clouds.' },
  { title: 'The Pig', text: 'The pig lives on the farm. It is pink and round. It rolls in the mud. Oink oink oink. The pig is happy in the mud.' },
  { title: 'My Crayons', text: 'I have a box of crayons. I drew a house. I drew a tree. I drew my family. I used every color in the box.' },
  { title: 'The Elephant', text: 'The elephant is very big. It has a long trunk. It has big ears. It drinks water with its trunk. I saw one at the zoo.' },
  { title: 'The Cake', text: 'Today is my birthday. Mom made a cake. It has five candles on it. I made a wish. I blew out all the candles.' },
  { title: 'The Boat', text: 'We went on a boat ride. The boat went on the lake. The water was blue. I saw fish in the water. It was a fun ride.' },
  { title: 'The Lion', text: 'The lion is the king of the jungle. It has a big mane. It can roar very loud. Roar roar roar. The lion is strong and brave.' },
  { title: 'My Blanket', text: 'I have a soft blanket. It is blue with stars on it. I cuddle with it at night. It keeps me warm. I love my blanket.' },
  { title: 'The Monkey', text: 'The monkey lives in the trees. It swings from branch to branch. It eats bananas. It has a long tail. The monkey is very funny.' },
  { title: 'The Rocket', text: 'I want to ride a rocket. It goes up to space. I would see the moon and stars. I would float in the air. Zoom zoom to the moon.' },
  { title: 'The Ladybug', text: 'I found a ladybug on a leaf. It was red with black dots. It crawled on my finger. It opened its wings. Then it flew away.' },
  { title: 'The Snowflake', text: 'A snowflake fell on my nose. It was cold and tiny. Each snowflake is different. I caught one on my glove. It melted right away.' },
  { title: 'The Pizza', text: 'We had pizza for dinner. It had cheese on top. It was hot and yummy. I ate two big slices. Pizza is my favorite food.' },
];
